$(document).ready(function() {
    $("#newDateOfContract").datepicker({
        monthNames:["Январь","Февраль","Март","Апрель","Май","Июнь","Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь"],
        dayNamesMin:["Пн","Вт","Ср","Чт","Пт","Сб","Вс"],
        firstDay:1,
        dateFormat:"yy-mm-dd"
    });
    $("#newDateOfStartContract").datepicker({
        monthNames:["Январь","Февраль","Март","Апрель","Май","Июнь","Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь"],
        dayNamesMin:["Пн","Вт","Ср","Чт","Пт","Сб","Вс"],
        firstDay:1,
        dateFormat:"yy-mm-dd"
    });
    $("#newDateOfEndContract").datepicker({
        monthNames:["Январь","Февраль","Март","Апрель","Май","Июнь","Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь"],
        dayNamesMin:["Пн","Вт","Ср","Чт","Пт","Сб","Вс"],
        firstDay:1,
        dateFormat:"yy-mm-dd"
    });
    $("#dateOfContract").datepicker({
        monthNames:["Январь","Февраль","Март","Апрель","Май","Июнь","Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь"],
        dayNamesMin:["Пн","Вт","Ср","Чт","Пт","Сб","Вс"],
        firstDay:1,
        dateFormat:"yy-mm-dd"
    });
    $("#dateOfStartContract").datepicker({
        monthNames:["Январь","Февраль","Март","Апрель","Май","Июнь","Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь"],
        dayNamesMin:["Пн","Вт","Ср","Чт","Пт","Сб","Вс"],
        firstDay:1,
        dateFormat:"yy-mm-dd"
    });
    $("#dateOfEndContract").datepicker({
        monthNames:["Январь","Февраль","Март","Апрель","Май","Июнь","Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь"],
        dayNamesMin:["Пн","Вт","Ср","Чт","Пт","Сб","Вс"],
        firstDay:1,
        dateFormat:"yy-mm-dd"
    });
});